title: Martinus Devlog
description: always be hustle 
author: Jongheon Lee
  avatar: /logo.JPG
  bio              : "**기록이 자산!!**<br>매일 공부하고 있습니다.<br>소통을 좋아합니다."
                     # biography의 약칭으로, 자기소개를 적으시면 됩니다.
                     # 줄바꿈은 <br>로 굵은 글씨는 **글씨** 로 표기해주세요. 
  location         : "Seoul ,Republic of Korea"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

skin: daylight

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.png
social:
  name: Jongheon Lee
  links:
    - https://github.com/martinuslee
    - https://instagram.com/bornin4march
lang: en
